### ISSUE TITLE
Updating to Qt5?

### ISSUE THREAD

**Issue by morberg** [jonasjj/oslo-quant#1]
First of all: very nice project, looks quite interesting!

Would you be open to moving to Qt5 instead of Qt4? I'm using macOS and Qt4 support is deprecated and quite tricky to get up and running. I had greater (initial) success modifying your code to use Qt5 than installing Qt4 on my system. Haven't tried everything yet though.

**Comment by jonasjj** [comment]
Thanks. Yes, I'm considering porting the plotting module to PyQt5. I tried to pull the project on macOS myself some time ago, just so that I could add the instructions to the Readme. I realized all the dependencies couldn't be installed only with homebrew, so I skipped it. If you want to share any code, please do.

Next, I plan to complete the simulate/strategy classes. Also, in the future I will be using the pandas.DataFrame class for storing ticker data, so that we can use the pandas libraries for analysis.
